### PR TITLE
Add function to calculate TOT

### PR DESCRIPTION
**Pull request by grey277**
Adding function to calculate TOT to JPetHit

### CODE REVIEW

**Comment by wkrzemien** [comment]
with the calculateTOT from EventCategorizersTools

**Comment by kkacprzak** [comment]
This method does the same as EventCategorizerTools::calculateTOT(hit), with the use of maps instead of vectors.
So do we want it here? I think calculating the TOT should be a part of reconstruction procedures, not a general data structure.

**Comment by grey277** [comment]
Generally yes, it should to the same.
One of the things with vector and sorting are missing thresholds, e.g if we will have from side A thr 1,2,3 and from side B 1,2,4 algorithm from EventCategorizerTools will calculate ToT over 3 thresholds and this algorithm will only include 2 first thresholds.
Beside of that on one of the framework meetings I think there was idea to add general method to calculate ToT to JPetHit object, but I could misunderstood something.

**Comment by kkacprzak** [comment]
Still, I think the method should be specific to the analysis/reconstruction. I.e. in the current SignalFinder, there is no possibility to create signal with occupied thresholds 1,2,4, without 3rd one. TOT calculation can be done in different ways for different analysis approaches. In the end we want to use it to express somehow the energy of the hit, but way of calculating this value is up to reconstruction. If we want a general, agreed-on TOT calculation, then lets add a field of TOT to JPetHit structure and fill it in the reconstruction.

**Comment by wkrzemien** [comment]
The function will be added to examples, so I am closing this PR

**Pull request closed without merging**
