### PR TITLE
[WIP] Add Jenkinsfile

### PR DESCRIPTION
**Pull request by kamilrakoczy**
This PR is still WIP.

### CODE REVIEW

**Comment by alekgajos** [comment]
Sorry, I have broken the master branch by mistake. I will reopen your PR once it is fixed.

**Comment by alekgajos** [comment]
Sorry for he confusion. Due to my mistake I had to delete and re-create the master branch.

**Comment by alekgajos** [comment]
Please also note that there was a merge to master from develop for the 9.0.0 release.

**Comment by JPETTomographyTester** [comment]
Found 1 violations:

**Reporter**: cppcheck-matrix-raporter
**Rule**: variableScope
**Severity**: INFO
**File**: /var/jenkins_home/workspace/J-Pet-Framework-matrix-job/boost_version/boost_1_58/cmake/cmake351/gcc/default_gcc/os/ubuntu16/root/root612/src/Core/JPetTaskStreamIO/JPetTaskStreamIO.cpp L85

The scope of the variable &#39;ok&#39; can be reduced. Warning: Be careful when fixing this message, especially when there are inner loops. Here is an example where cppcheck will write that the scope for &#39;i&#39; can be reduced:\012void f(int x)\012{\012    int i &#61; 0;\012    if (x) {\012        // it&#39;s safe to move &#39;int i &#61; 0;&#39; here\012        for (int n &#61; 0; n &lt; 10; ++n) {\012            // it is possible but not safe to move &#39;int i &#61; 0;&#39; here\012            do_something(&amp;i);\012        }\012    }\012}\012When you see this message it is always safe to reduce the variable scope 1 level.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a597324643>*

 *<ACCUMULATED-VIOLATIONS>*

**Comment by JPETTomographyTester** [comment]
Found 1 violations:

**Reporter**: cppcheck-matrix-raporter
**Rule**: variableScope
**Severity**: INFO
**File**: /var/jenkins_home/workspace/J-Pet-Framework-matrix-job/boost_version/boost_1_58/cmake/cmake315/gcc/default_gcc/os/ubuntu16/root/root618/src/Core/JPetTaskStreamIO/JPetTaskStreamIO.cpp L85

The scope of the variable &#39;ok&#39; can be reduced. Warning: Be careful when fixing this message, especially when there are inner loops. Here is an example where cppcheck will write that the scope for &#39;i&#39; can be reduced:\012void f(int x)\012{\012    int i &#61; 0;\012    if (x) {\012        // it&#39;s safe to move &#39;int i &#61; 0;&#39; here\012        for (int n &#61; 0; n &lt; 10; ++n) {\012            // it is possible but not safe to move &#39;int i &#61; 0;&#39; here\012            do_something(&amp;i);\012        }\012    }\012}\012When you see this message it is always safe to reduce the variable scope 1 level.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1731412495>*

 *<ACCUMULATED-VIOLATIONS>*

**Comment by JPETTomographyTester** [comment]
Found 1 violations:

**Reporter**: cppcheck-matrix-raporter
**Rule**: variableScope
**Severity**: INFO
**File**: /var/jenkins_home/workspace/J-Pet-Framework-matrix-job/boost_version/boost_1_58/cmake/cmake351/gcc/default_gcc/os/ubuntu16/root/root612/src/Core/JPetTaskStreamIO/JPetTaskStreamIO.cpp L85

The scope of the variable &#39;ok&#39; can be reduced. Warning: Be careful when fixing this message, especially when there are inner loops. Here is an example where cppcheck will write that the scope for &#39;i&#39; can be reduced:\012void f(int x)\012{\012    int i &#61; 0;\012    if (x) {\012        // it&#39;s safe to move &#39;int i &#61; 0;&#39; here\012        for (int n &#61; 0; n &lt; 10; ++n) {\012            // it is possible but not safe to move &#39;int i &#61; 0;&#39; here\012            do_something(&amp;i);\012        }\012    }\012}\012When you see this message it is always safe to reduce the variable scope 1 level.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a597324643>*

 *<ACCUMULATED-VIOLATIONS>*

**Pull request closed without merging**
