### PR TITLE
Bz2 and zip unpacking (redmine #914)

### PR DESCRIPTION
**Pull request by kkacprzak**
Added bz2 and zip unpacking hld file before task run.
http://sphinx.if.uj.edu.pl/redmine/issues/914

### CODE REVIEW

**Comment by grey277** [comment]
retest this please

**Comment by kkacprzak** [comment]
I added missing zip files to sphinx unit test data. Is is possible to rerun tests here? It was the only error that occurred in logs.

**Comment by grey277** [comment]
To force rerun tests, you need to type: "retest this please", it sends signal to Travis/Jenkins, and run tests.

**Comment by kkacprzak** [comment]
retest this please

**Pull request merged**
