### PR TITLE
Direct streaming of data through tasks without intermediate files (for v10)

### PR DESCRIPTION
**Pull request by alekgajos**
This version adds optional processing without producing intermediate files.
It is enabled with the -d command line option.

This is a new version of this feature applied on top of v9.
This PR supersedes: #191.

### CODE REVIEW

**Comment by JPETTomographyTester** [comment]
Found 1 violations:

**Reporter**: cppcheck-matrix-raporter
**Rule**: variableScope
**Severity**: INFO
**File**: src/Core/JPetTaskStreamIO/JPetTaskStreamIO.cpp L85

The scope of the variable &#39;ok&#39; can be reduced. Warning: Be careful when fixing this message, especially when there are inner loops. Here is an example where cppcheck will write that the scope for &#39;i&#39; can be reduced:\012void f(int x)\012{\012    int i &#61; 0;\012    if (x) {\012        // it&#39;s safe to move &#39;int i &#61; 0;&#39; here\012        for (int n &#61; 0; n &lt; 10; ++n) {\012            // it is possible but not safe to move &#39;int i &#61; 0;&#39; here\012            do_something(&amp;i);\012        }\012    }\012}\012When you see this message it is always safe to reduce the variable scope 1 level.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a243367213>*

 *<ACCUMULATED-VIOLATIONS>*

**Comment by JPETTomographyTester** [comment]
Found 1 violations:

**Reporter**: cppcheck-matrix-raporter
**Rule**: variableScope
**Severity**: INFO
**File**: src/Core/JPetTaskStreamIO/JPetTaskStreamIO.cpp L85

The scope of the variable &#39;ok&#39; can be reduced. Warning: Be careful when fixing this message, especially when there are inner loops. Here is an example where cppcheck will write that the scope for &#39;i&#39; can be reduced:\012void f(int x)\012{\012    int i &#61; 0;\012    if (x) {\012        // it&#39;s safe to move &#39;int i &#61; 0;&#39; here\012        for (int n &#61; 0; n &lt; 10; ++n) {\012            // it is possible but not safe to move &#39;int i &#61; 0;&#39; here\012            do_something(&amp;i);\012        }\012    }\012}\012When you see this message it is always safe to reduce the variable scope 1 level.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1722862945>*

 *<ACCUMULATED-VIOLATIONS>*

**Review by kkacprzak — CHANGES_REQUESTED** [review]
This PR will greatly improve data processing for our analyses, good job. I have checked the code and made a test runs, on my private laptop direct processing reduces time to about 60% of non-direct one. I have minor remarks to the code.

**Comment by alekgajos** [comment]
Sorry for the confusion. I was not aware that merging branches through GitHub would destroy the develop branch but it did. Please ignore the temporary closing of this PR.

**Comment by JPETTomographyTester** [comment]
Found 1 violations:

**Reporter**: cppcheck-matrix-raporter
**Rule**: variableScope
**Severity**: INFO
**File**: src/Core/JPetTaskStreamIO/JPetTaskStreamIO.cpp L85

The scope of the variable &#39;ok&#39; can be reduced. Warning: Be careful when fixing this message, especially when there are inner loops. Here is an example where cppcheck will write that the scope for &#39;i&#39; can be reduced:\012void f(int x)\012{\012    int i &#61; 0;\012    if (x) {\012        // it&#39;s safe to move &#39;int i &#61; 0;&#39; here\012        for (int n &#61; 0; n &lt; 10; ++n) {\012            // it is possible but not safe to move &#39;int i &#61; 0;&#39; here\012            do_something(&amp;i);\012        }\012    }\012}\012When you see this message it is always safe to reduce the variable scope 1 level.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1731412495>*

 *<ACCUMULATED-VIOLATIONS>*

**Comment by JPETTomographyTester** [comment]
Found 1 violations:

**Reporter**: cppcheck-matrix-raporter
**Rule**: variableScope
**Severity**: INFO
**File**: src/Core/JPetTaskStreamIO/JPetTaskStreamIO.cpp L85

The scope of the variable &#39;ok&#39; can be reduced. Warning: Be careful when fixing this message, especially when there are inner loops. Here is an example where cppcheck will write that the scope for &#39;i&#39; can be reduced:\012void f(int x)\012{\012    int i &#61; 0;\012    if (x) {\012        // it&#39;s safe to move &#39;int i &#61; 0;&#39; here\012        for (int n &#61; 0; n &lt; 10; ++n) {\012            // it is possible but not safe to move &#39;int i &#61; 0;&#39; here\012            do_something(&amp;i);\012        }\012    }\012}\012When you see this message it is always safe to reduce the variable scope 1 level.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a597324643>*

 *<ACCUMULATED-VIOLATIONS>*

**Comment by alekgajos** [comment]
@kkacprzak, I have implemented all of your suggestions. Please have a look and let me know if we need anything more.
@wkrzemien, please submit submit a review.

**Review by wkrzemien — COMMENTED** [review]
I still need a bit of time to think about the general architecture - it is not about the solution you proposed rather what we have up to now. I am on it.

**Comment by alekgajos** [comment]
@wkrzemien, I have tested your PR and merged your suggested changes into this PR.

**Comment by alekgajos** [comment]
@kamilrakoczy cpould you take a look at the failign Jenkins test? I do not know what is the difference between this one and the other which is passing (the build steps seem the same).

**Comment by kamilrakoczy** [comment]
@alekgajos I'm not really sure, what is the problem, but it seems that rebasing on current develop (see #271) (after new Jenkinsfile configuration was added) fixes the problem:
```
git fetch origin
git rebase origin/develop
git push upstream direct --force
```

**Comment by alekgajos** [comment]
@kamilrakoczy, thank you for the rebasing suggestion - ultimately it solved the problem with tests.
Just a strange observation: After force-pushing the rebased PR, the jenkins/pr-merge test was still failing but it must have been an artifact of testing this particular PR as the test status was automatically changed to passing once I created a copy of this PR with the same content (#273), for which all tests passed.

**Comment by alekgajos** [comment]
@wkrzemien All of the tests are passing now. Please have a final look at this PR. Unless you have additional comments, I think it is ready for merging.

**Pull request merged**
