### PR TITLE
Direct streaming of data through tasks without intermediate files

### PR DESCRIPTION
**Pull request by alekgajos**
This version adds optional processing without producing intermediate files.
It is enabled with the -d command line option.

### CODE REVIEW

**Comment by alekgajos** [comment]
After version 7.0 release, I would like to resume the discussion on this PR as it allows to speed up data processing by about 3x and strongly reduces disk usage per HLD file.

**Comment by alekgajos** [comment]
It was recently discovered that these changes do not work with MCGeantParser results.
It will be investigated and corrected. Please hold with the review.

**Comment by wkrzemien** [comment]
Some conflict appeared

**Comment by JPETTomographyTester** [comment]
Found 6 violations:

**Reporter**: cppcheck-raporter
**Rule**: redundantAssignment
**Severity**: INFO
**File**: /var/jenkins_home/workspace/J-Pet-Framework-matrix-job/boost_version/boost_1_58/gcc_version/gcc-5.4.0/root_version/root_v6.08.06/src/Core/JPetTaskIO/JPetTaskIO.cpp L108

Variable &#39;isOK&#39; is reassigned a value before the old one has been used.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1570647532>*
**Reporter**: cppcheck-raporter
**Rule**: redundantAssignment
**Severity**: INFO
**File**: /var/jenkins_home/workspace/J-Pet-Framework-matrix-job/boost_version/boost_1_58/gcc_version/gcc-5.4.0/root_version/root_v6.08.06/src/Core/JPetTaskIO/JPetTaskIO.cpp L106

Variable &#39;isOK&#39; is reassigned a value before the old one has been used.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-966254892>*
**Reporter**: cppcheck-raporter
**Rule**: passedByValue
**Severity**: INFO
**File**: /var/jenkins_home/workspace/J-Pet-Framework-matrix-job/boost_version/boost_1_58/gcc_version/gcc-5.4.0/root_version/root_v6.08.06/src/Options/JPetOptionsGenerator/JPetOptionsGeneratorTools.cpp L181

Function parameter &#39;fileType&#39; should be passed by reference.. Parameter &#39;fileType&#39; is passed by value. It could be passed as a (const) reference which is usually faster and recommended in C++.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a573960529>*
**Reporter**: cppcheck-raporter
**Rule**: passedByValue
**Severity**: INFO
**File**: /var/jenkins_home/workspace/J-Pet-Framework-matrix-job/boost_version/boost_1_58/gcc_version/gcc-5.4.0/root_version/root_v6.08.06/src/Options/JPetOptionsGenerator/JPetOptionsGeneratorTools.cpp L189

Function parameter &#39;file&#39; should be passed by reference.. Parameter &#39;file&#39; is passed by value. It could be passed as a (const) reference which is usually faster and recommended in C++.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1122237302>*
**Reporter**: cppcheck-raporter
**Rule**: passedByValue
**Severity**: INFO
**File**: /var/jenkins_home/workspace/J-Pet-Framework-matrix-job/boost_version/boost_1_58/gcc_version/gcc-5.4.0/root_version/root_v6.08.06/src/Options/JPetOptionsGenerator/JPetOptionsGeneratorTools.cpp L191

Function parameter &#39;path&#39; should be passed by reference.. Parameter &#39;path&#39; is passed by value. It could be passed as a (const) reference which is usually faster and recommended in C++.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a710861623>*
**Reporter**: cppcheck-raporter
**Rule**: useInitializationList
**Severity**: INFO
**File**: /var/jenkins_home/workspace/J-Pet-Framework-matrix-job/boost_version/boost_1_58/gcc_version/gcc-5.4.0/root_version/root_v6.08.06/tests/Options/JPetOptionsGenerator/JPetOptionsGeneratorTest.cpp L255

Variable &#39;fInputFile&#39; is assigned in constructor body. Consider performing initialization in initialization list.. When an object of a class is created, the constructors of all member variables are called consecutively in the order the variables are declared, even if you don&#39;t explicitly write them to the initialization list. You could avoid assigning &#39;fInputFile&#39; a value by passing the value to the constructor in the initialization list.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1137109835>*
 *<ACCUMULATED-VIOLATIONS>*

**Comment by wkrzemien** [comment]
It seems that there is still an unsolved conflict:
Options/JPetOptionsTools/JPetOptionsTools.cpp

**Comment by alekgajos** [comment]
Superseded by #259.

**Pull request closed without merging**
